services:
  litellm:
    env_file:
      - .env
    image: docker.litellm.ai/berriai/litellm:main-latest
    ports:
      - "127.0.0.1:4000:4000"
    volumes:
      - ./infra/litellm/config.yaml:/app/config.yaml:ro
    environment:
      - JSON_LOGS=True
      - LITELLM_LOG=ERROR
    command: --config /app/config.yaml --detailed_debug
    restart: unless-stopped
